# Configure main menu and social menu
[[main]]
identifier = "resume"
name = "Resume"
url = "/"

[main.params]
icon = "menu-resume"
newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ganesh-shivkumar"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/ganesh-shivkumar"

[social.params]
icon = "brand-linkedin"
